#!/usr/bin/env ruby

require "timeout"

OFFLINEIMAP_MAX_SEC     = 60 * 5
SLEEP_SEC_AFTER_FAILURE = 30
SLEEP_SEC_AFTER_SUCCESS = 60 * 20

OFFLINEIMAP_COMMAND = %W(
  timeout
  --kill-after 10s
  --signal 15
  --preserve-status
  #{OFFLINEIMAP_MAX_SEC}
  offlineimap
).join(" ")

def sleepx(n)
  STDIN.flush
  result = nil
  begin
    Timeout::timeout(n) { STDIN.readline }
    result = true
  rescue Timeout::Error
    result = false
  rescue EOFError
  end
  result
end

def say(s)
  STDOUT.puts "[#{s}]"
end

def run(c)
  system(c)
  $? == 0
end

def quit
  say "quitting"
  exit
end

trap("INT") { quit }

loop do
  loop do
    say "checking"
    break if run OFFLINEIMAP_COMMAND
    say "failed, sleeping"
    sleep SLEEP_SEC_AFTER_FAILURE
  end

  if sleepx(SLEEP_SEC_AFTER_SUCCESS).nil?
    quit
  end
end
