#!/usr/bin/env lua

-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --

local engines = {
  l = { nb = '#404040', nf = '#ffffff', p = 'Arch',               url = 'http://www.archlinux.org/packages/?q='                                                 },
  L = { nb = '#404040', nf = '#ffffff', p = 'Arch [AUR]',         url = 'http://aur.archlinux.org/packages.php?K='                                              },
  G = { nb = '#404040', nf = '#ffffff', p = 'github',             url = 'http://github.com/search?x=0&y=0&q='                                                   },
  i = { nb = '#404040', nf = '#ffffff', p = 'Google Images',      url = 'http://images.google.com/images?q='                                                    },
  d = { nb = '#404040', nf = '#ffffff', p = 'dictionary',         url = 'http://dictionary.reference.com/browse/'                                               },
  g = { nb = '#404040', nf = '#ffffff', p = 'duckduckgo',         url = 'https://duckduckgo.com?kp=-1&kl=wt-wt&kh=1&q='                                         },
--g = { nb = '#404040', nf = '#ffffff', p = 'Google',             url = 'https://encrypted.google.com/search?num=100&q='                                        },
  h = { nb = '#404040', nf = '#ffffff', p = 'Hoogle',             url = 'http://www.haskell.org/hoogle/?q='                                                     },
  H = { nb = '#404040', nf = '#ffffff', p = 'Hackage',            url = 'http://www.google.com/search?hl=en&as_sitesearch=hackage.haskell.org%2Fpackages&as_q=' },
  t = { nb = '#404040', nf = '#ffffff', p = 'thesaurus',          url = 'http://thesaurus.reference.com/search?q='                                              },
  w = { nb = '#404040', nf = '#ffffff', p = 'Wikipedia',          url = 'https://secure.wikimedia.org/wikipedia/en/wiki/Special:Search?go=Go&search='           },
  y = { nb = '#404040', nf = '#ffffff', p = 'YouTube',            url = 'http://www.youtube.com/results?search_type=search_videos&search_query='                },
  r = { nb = '#404040', nf = '#ffffff', p = 'RubyGems',           url = 'http://rubygems.org/search?utf8=%E2%9C%93&query='                                      },
}

-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --

function urlencode(s)
  if s then
    s = string.gsub(s, '\n', '\r\n')
    s = string.gsub(s, '([^%w ])', function(c) return string.format('%%%02X', string.byte(c)) end)
    s = string.gsub(s, ' ', '+')
  end
  return s
end

function quote(s)
  return '\''..s..'\''
end

function make_dmenu_command(engine)
  local command = 'echo -n | dmenu -b -fn '..quote('-*-terminus-medium-*-*-*-16-*-*-*-*-*-*-*')

  for i,v in ipairs({ 'p', 'nb', 'nf', 'sb', 'sf' }) do
    if engine[v] then
      command = command..' -'..v..' '..quote(engine[v])
    end
  end

  return command
end

function get_search_term(engine)
  local command = make_dmenu_command(engine)
  local h = io.popen(command, 'r')
  local term = h:read()
  return term
end

-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --

if #arg ~= 1 and #arg ~= 2 then
  print "usage: <engine> [search-term]"
  os.exit(1)
end

if arg[1]:len() ~= 1 then
  print "engine must be one character in length"
  os.exit(1)
end

local engine = engines[arg[1]]
if not engine then
  print "invalid engine"
  os.exit(1)
end

if #arg == 2 then
  term = arg[2]
else
  term = get_search_term(engine)
end

if term and term:len() > 0 then
  u = engine.url..urlencode(term)
  if u then
    os.execute('open-url '..quote(u))
  end
end
